---
# 应用服务 WEB 访问端口
server:
  port: 9090

# MyBatis 配置


# Spring 配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-vue?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: Ggb1415926



